### ISSUE TITLE
Scale, max-width and max-heigh parameters

### ISSUE THREAD

**Issue by tzwaan** [demodude4u/Factorio-FBSR#116]
I'd like to request a feature for the webapi to accept the scale, max-width and max-height in the headers of the post request.

If the generated image exceeds either the max-width or max-height, it should scale the entire thing down to that maximum value.

If scale is set, it should scale the entire picture by that amount.

Scale should only work as long as the image doesn't get bigger than the maximum values, if they're set.

**Comment by demodude4u** [comment]
I sorta addressed this issue with 62a600320a4a89cc089ffb78535df2349fdff4e0.

The differences though, is that the options are passed along in the body, not the header, and there is no scale option.

I will close this issue because I believe the commit was sufficient, but if you feel that there is more value to be added, please open another issue. 🙂
